### ISSUE TITLE
ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by JuriHaataja** [passwordless-id/webauthn#42]
I'm running this library with Firebase Functions and for some reason it's unable to use the crypto library that should be built-in in Node v20.

More detailed logs:
```
ReferenceError: crypto is not defined
at parseCryptoKey (file:///workspace/node_modules/@passwordless-id/webauthn/dist/esm/server.js:92:5)
    at verifySignature (file:///workspace/node_modules/@passwordless-id/webauthn/dist/esm/server.js:107:27)
    at Module.verifyAuthentication (file:///workspace/node_modules/@passwordless-id/webauthn/dist/esm/server.js:31:36)
```

**Comment by JuriHaataja** [comment]
Update:
```
"engines": {
    "node": "20"
  },
```
For some reason my node version wasn't synced (it was using v18) with local changes when deployed to cloud.
