### ISSUE TITLE
Error: ReferenceError: module is not defined in ES module scope in SvelteKit/Vite

### ISSUE THREAD

**Issue by hjaber** [passwordless-id/webauthn#60]
Thank you for the big V2 update! While migrating, I encountered an error and reproduced it on a clean install with SvelteKit:

```bash
10:48:46 AM [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "@passwordless-id/webauthn"
|- ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/hj/Documents/dev/passwordless/node_modules/@passwordless-id/webauthn/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/hj/Documents/dev/passwordless/node_modules/@passwordless-id/webauthn/dist/cjs/index.js:30:1
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
    at async nodeImport (file:///Users/hj/Documents/dev/passwordless/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52735:15)
    at async ssrImport (file:///Users/hj/Documents/dev/passwordless/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52591:16)
    at async eval (/Users/hj/Documents/dev/passwordless/src/routes/+page.svelte:4:31)
    at async instantiateModule (file:///Users/hj/Documents/dev/passwordless/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52650:5)
```

```bash
# reproduce
npm create svelte@latest my-app
cd my-app
npm install
npm install @passwordless-id/webauthn
npm run dev
```

```svelte
<!-- /src/routes/+page.svelte -->
<script lang="ts">
  import { client } from "@passwordless-id/webauthn";

  async function registerUser() {
    await client.register({
      challenge: "a random string generated by the server",
      user: "John Doe",
    });
  }
</script>

<h1>Welcome to SvelteKit</h1>
<p>
  Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation
</p>
```

```bash
  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 3.50 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.3.0 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.7.6 - /usr/local/bin/pnpm
    bun: 1.1.20 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 127.1.68.128
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @passwordless-id/webauthn: ^2.0.0 => 2.0.0 
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.2 
    @sveltejs/kit: ^2.0.0 => 2.5.18 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.1 
    svelte: ^4.2.7 => 4.2.18 
    vite: ^5.0.3 => 5.3.5 
```

**Comment by dagnelies** [comment]
Thanks for the quality report. I'll take a look at it in the coming days.

**Comment by dagnelies** [comment]
Please try it again with v2.0.1

**Comment by mcm-ham** [comment]
That fixed it for me.

**Comment by hjaber** [comment]
Thank you for your prompt fix, https://github.com/passwordless-id/webauthn/commit/8fdc63af65d527cb5cb3618271cd52f2641a2f77 appears to have fixed the issue I'm having with vite/sveltekit!
